Improve how return value of certain commands are checked

diff --git a/bin/tmuxifier b/bin/tmuxifier
--- a/bin/tmuxifier
+++ b/bin/tmuxifier
@@ -24,10 +24,9 @@ case "$command" in
     ;;
 
   * )
+    # Lookup command, attempt to resolve as alias if fails
     ! command_path="$(command -v "tmuxifier-$command")"
-
-    # Attempt to resolve aliases
-    if [ -z "$command_path" ]; then
+    if [ ! -n $? ]; then
       resolved="$(tmuxifier-alias "$command")"
       if [ ! -z "$resolved" ]; then
         ! command_path="$(command -v "tmuxifier-$resolved")"
diff --git a/libexec/tmuxifier-completions b/libexec/tmuxifier-completions
--- a/libexec/tmuxifier-completions
+++ b/libexec/tmuxifier-completions
@@ -18,10 +18,9 @@ if [ -z "$command" ]; then
   exit 1
 fi
 
+# Lookup command, attempt to resolve as alias if fails
 ! command_path="$(command -v "tmuxifier-$command")"
-
-# Attempt to resolve aliases
-if [ -z "$command_path" ]; then
+if [ ! -n $? ]; then
   resolved="$(tmuxifier-alias "$command")"
   if [ ! -z "$resolved" ]; then
     ! command_path="$(command -v "tmuxifier-$resolved")"
diff --git a/libexec/tmuxifier-help b/libexec/tmuxifier-help
--- a/libexec/tmuxifier-help
+++ b/libexec/tmuxifier-help
@@ -9,10 +9,10 @@ if [ "$1" == "--complete" ]; then
 fi
 
 command="$1"
-! command_path="$(command -v "tmuxifier-$command")"
 
-# Attempt to resolve aliases
-if [ -z "$command_path" ]; then
+# Lookup command, attempt to resolve as alias if fails
+! command_path="$(command -v "tmuxifier-$command")"
+if [ ! -n $? ]; then
   resolved="$(tmuxifier-alias "$command")"
   if [ ! -z "$resolved" ]; then
     command="$resolved"
