Check for minimum required Tmux version (fixed #37)

diff --git a/bin/tmuxifier b/bin/tmuxifier
--- a/bin/tmuxifier
+++ b/bin/tmuxifier
@@ -31,6 +31,13 @@ source "$TMUXIFIER/lib/env.sh"
 
 export PATH="$TMUXIFIER/libexec:$PATH"
 
+export TMUXIFIER_MIN_TMUX_VERSION="1.6"
+if [ "$(tmuxifier-tmux-version "$TMUXIFIER_MIN_TMUX_VERSION")" == "<" ]; then
+  echo -e "ERROR: Tmuxifier requires Tmux v${TMUXIFIER_MIN_TMUX_VERSION}" \
+       "or newer. You have v$(tmuxifier-tmux-version)." >&2
+  exit 1
+fi
+
 command="$1"
 case "$command" in
   "" | "-h" | "--help" )
