added customizable template directory

diff --git a/libexec/tmuxifier-new-session b/libexec/tmuxifier-new-session
--- a/libexec/tmuxifier-new-session
+++ b/libexec/tmuxifier-new-session
@@ -29,7 +29,7 @@ fi
 layout_name="$1"
 session_path="$TMUXIFIER_SESSION_BASE_PATH/${layout_name}"
 layout_file="$TMUXIFIER_LAYOUT_PATH/${layout_name}.session.sh"
-template="$TMUXIFIER/templates/session.sh"
+template="$TMUXIFIER_TEMPLATE_PATH/session.sh"
 
 if [ $# -eq 2 ]; then
   if [ "$2" == "." ]; then
@@ -43,7 +43,7 @@ fi
 session_path=${session_path//$HOME/"~"}
 
 if [ ! -f "$template" ]; then
-  echo "tmuxifier: session layout template not found: $template" >&2
+  echo "tmuxifier: session layout template not found \"$template\"" >&2
   exit 1
 fi
 
